server:
  port: 8080

spring:
  application:
    name: biometrics-demo
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: local

sunedu:
  api:
    attach: /api/v1/Carne/imagen/adjuntar
    list: /bi/v1/ImagenResultado/listarParametrosValor


